@startuml
left to right direction
actor Client
actor Administrator
actor Engenieer

rectangle Sistema {
  Client --> (Request proyect)
  Client --> (Consultar informes)
  Administrator --> (Gestionar usuarios)
  Administrator --> (Log in)
}
Administrator --> (Start Business Process)
@enduml
